language: node_js
node_js:
  - lts/*

install:
 - npm install

services:
- postgresql
env:
- DB_USERNAME=eben DB_PASSWORD=password DBNAME=store_manager
before_script:
- psql -c 'create database store_manager;' -U postgres
- psql -c "CREATE USER eben WITH PASSWORD 'password';" -U postgres

scripts: npm run test

script:
  - nyc --reporter=lcov npm run test

after_script:
  - npm run coverage
